package com.gloria.hibernate;

// Generated Jul 6, 2012 9:04:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "function", catalog = "gloria")
public class Function implements java.io.Serializable {

	private Integer functionid;
	private String roleid;

	public Function() {
	}

	public Function(String roleid) {
		this.roleid = roleid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "functionid", unique = true, nullable = false)
	public Integer getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(Integer functionid) {
		this.functionid = functionid;
	}

	@Column(name = "roleid", nullable = false, length = 45)
	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}
