package com.gloria.hibernate;

// Generated Jul 6, 2012 9:04:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Institution generated by hbm2java
 */
@Entity
@Table(name = "institution", catalog = "gloria")
public class Institution implements java.io.Serializable {

	private Integer institutionId;
	private String staffId;
	private String studentId;

	public Institution() {
	}

	public Institution(String staffId, String studentId) {
		this.staffId = staffId;
		this.studentId = studentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INSTITUTION_ID", unique = true, nullable = false)
	public Integer getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}

	@Column(name = "STAFF_ID", nullable = false, length = 45)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "STUDENT_ID", nullable = false, length = 45)
	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

}
