package com.gloria.hibernate;

// Generated Jul 6, 2012 9:04:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "gloria")
public class Staff implements java.io.Serializable {

	private Integer staffid;
	private int studentid;
	private Date dob;

	public Staff() {
	}

	public Staff(int studentid, Date dob) {
		this.studentid = studentid;
		this.dob = dob;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STAFFID", unique = true, nullable = false)
	public Integer getStaffid() {
		return this.staffid;
	}

	public void setStaffid(Integer staffid) {
		this.staffid = staffid;
	}

	@Column(name = "studentid", nullable = false)
	public int getStudentid() {
		return this.studentid;
	}

	public void setStudentid(int studentid) {
		this.studentid = studentid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", nullable = false, length = 0)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

}
