package com.gloria.hibernate;

// Generated Jul 6, 2012 9:04:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Timetable generated by hbm2java
 */
@Entity
@Table(name = "timetable", catalog = "gloria")
public class Timetable implements java.io.Serializable {

	private Integer staffid;

	public Timetable() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Staffid", unique = true, nullable = false)
	public Integer getStaffid() {
		return this.staffid;
	}

	public void setStaffid(Integer staffid) {
		this.staffid = staffid;
	}

}
